baseURL = "https://elikesbikes.com/"
languageCode = "en"
title = "Emmanuel Loaiza (tars)"
theme = "blowfish"
defaultContentLanguage = "en"

# Enable tags for Topics page
[taxonomies]
  tag = "tags"

# Keep draft and future content visible when testing locally
buildDrafts = true
buildFuture = true

# You can tweak site metadata later here
[params]
  mainSections = ["videos"]
