[[main]]
  name = "Videos"
  pageRef = "videos"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 30

[[main]]
  name = "homelab"
  pageRef = "resources/homelab"
  parent = "Resources"
  weight = 31

[[main]]
  name = "tutorials"
  pageRef = "resources/tutorials"
  parent = "Resources"
  weight = 32

[[main]]
  name = "linux_dotfiles"
  pageRef = "resources/linux_dotfiles"
  parent = "Resources"
  weight = 33

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 40
