[[main]]
  name = "Videos"
  pageRef = "videos"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 30

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 40
